### ISSUE TITLE
Write documentation showing how the counter works.

### ISSUE THREAD

**Issue by DGKSK8LIFE** [gallo-json/juggle-counter#1]
(nice program btw; you're POGCHAMP developer)

**Comment by gallo-json** [comment]
Thanks lol. So far it can only track the ball. I'll have to figure out how to actualy count the number of juggles (probably with ball coordinates)

**Comment by DGKSK8LIFE** [comment]
> Thanks lol. So far it can only track the ball. I'll have to figure out how to actualy count the number of juggles (probably with ball coordinates)

Oh nice. Yeah; I think for something like this, doing vanilla computer vision will be too difficult, what you could do, is use an AI model that can recognize shoes and a ball, then figure out whether the ball comes into contact with the shoe, and if so, increment a counter by one. Actually, something that would be really nice that you could integrate this app into, is OBS. You can make this into an OBS Plugin if you wanted.

**Comment by gallo-json** [comment]
That's an interesting idea, but many times soccer players with start juggling with other body parts like their head, chest, knee, etc not only feet. Also, I dont understand what you mean by an OBS plugin. The open broadcaster software?

**Comment by DGKSK8LIFE** [comment]
> That's an interesting idea, but many times soccer players with start juggling with other body parts like their head, chest, knee, etc not only feet. Also, I dont understand what you mean by an OBS plugin. The open broadcaster software?

Yes open broadcaster software, like if you wanted to (or your brother wanted to) live stream you juggling a soccer ball, you could have all the processing going on behind the scenes and then showing a little `juggles-count` jumper and incrementing it for example. Yeah you could use a body detection model, and count any contact with the human a juggle?!
